using JustyBase.NetezzaDriver;
using Microsoft.VisualStudio.TestPlatform.Utilities;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Data.Common;
using System.Data.Odbc;
using System.Diagnostics;
using System.Text;
using Xunit.Abstractions;

namespace TestProject;

public class BasicTests : IDisposable
{
    private const string _host = "linux.local";
    private const string _dbName = "JUST_DATA";
    private const string _userName = "admin";
    private static readonly string _password = Environment.GetEnvironmentVariable("NZ_DEV_PASSWORD") ?? throw new InvalidOperationException("Environment variable NZ_PASSWORD is not set.");
    private const int _port = 5480;

    DbConnection _odbcConnection;
    DbConnection _nzNewConnection;
    private readonly ITestOutputHelper _output;
    public BasicTests(ITestOutputHelper output)
    {
        _output = output;
        _odbcConnection = new OdbcConnection($"Driver={{NetezzaSQL}};servername={_host};port={_port};database={_dbName};username={_userName};password={_password};FastSelect=false");
        _odbcConnection.Open();

        _nzNewConnection = new NzConnection(_userName, _password, _host, _dbName, _port, logger: null);
        _nzNewConnection.Open();
    }


    //select
    //    'SELECT * FROM SYSTEM.ADMIN.' || TABLENAME
    //from SYSTEM.._V_TABLE;
    //select 'SELECT * FROM SYSTEM.ADMIN.' || VIEWNAME
    //from SYSTEM.._V_VIEW;
    private const string queryManyTypes =
        """
            SELECT  
            10::bigint
            , null ::bigint
            , true::Boolean -- ??
            , false::Boolean -- ??
            , null::Boolean
            , 5::Byteint
            , null::Byteint
            , 'a' :: Char
            , null :: Char
            , current_date::Date
            , null::Date
            , 0.5::float
            , null::float
            , 10::integer
            , null::integer
            , 'next should be 02:00:00 time'
            , '02:00:00'::TIME
            , 'abc' ::nchar(10)
            , null ::nchar(10)
            , 1.54::numeric(30, 6)
            , null::numeric(30, 6)
            , 'abc'::Nvarchar(10)
            , null::Nvarchar(10)
            , 1.54::real
            , null::real
            , 5::smallint
            , null::smallint
            --, current_time::time
            , '10:12:13'::TIME
            , null::time
            --, null::Timewithzone
            , DATE_TRUNC('hour',current_timestamp)::Timestamp
            , null:: Timestamp
            , 'abc' ::varchar(10)
            , null ::varchar(10)
             ,* 
            FROM JUST_DATA..FACTPRODUCTINVENTORY 
            order by rowid asc
            LIMIT 1
        """;

    private readonly string[] _queryListBasic =
    [
        "SELECT * FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1000",
        "SELECT false::BOOLEAN FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 15::BYTEINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 'ABC'::VARCHAR(10) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 'ABC'::NCHAR(10) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 'ABC'::NVARCHAR(10) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT '2024-12-12'::DATE FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT '2024-12-12'::TIMESTAMP FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT '12:15:17'::TIME FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 3.14::NUMERIC(10,4) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 3.14::NUMERIC(20,4) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 3.14::NUMERIC(30,4) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 3.14::NUMERIC(38,8) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 123456789::NUMERIC(38,0) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 923281625142643375987.43950777::numeric(38,8) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT -923281625142643375987.43950777::numeric(38,8) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 3.14::REAL FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 3.14::DOUBLE FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 3.14::FLOAT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 12345678::INTEGER FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 12345678::INT4 FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT -128::BYTEINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT -125::BYTEINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 127::BYTEINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 25000::SMALLINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 25000::SMALLINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT -9223372036854775808::BIGINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 9223372036854775807::BIGINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT 5223372036854775807::BIGINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
        "SELECT false::BOOLEAN",
        "SELECT 15::BYTEINT",
        "SELECT 'ABC'::VARCHAR(10)",
        "SELECT 'ABC'::NCHAR(10)",
        "SELECT 'ABC'::NVARCHAR(10)",
        "SELECT '2024-12-12'::DATE",
        "SELECT '2024-12-12'::TIMESTAMP",
        "SELECT '12:15:17'::TIME",
        "SELECT 3.14::NUMERIC(10,4)",
        "SELECT 3.14::NUMERIC(20,4)",
        "SELECT 3.14::NUMERIC(30,4)",
        "SELECT 3.14::NUMERIC(38,8)",
        "SELECT 123456789::NUMERIC(38,0)",
        "SELECT 923281625142643375987.43950777::numeric(38,8)",
        "SELECT -923281625142643375987.43950777::numeric(38,8)",
        "SELECT 3.14::REAL",
        "SELECT 3.14::DOUBLE",
        "SELECT 3.14::FLOAT",
        "SELECT 12345678::INTEGER",
        "SELECT 12345678::INT4",
        "SELECT -128::BYTEINT",
        "SELECT -125::BYTEINT",
        "SELECT 127::BYTEINT",
        "SELECT 25000::SMALLINT",
        "SELECT 25000::SMALLINT",
        "SELECT -9223372036854775808::BIGINT",
        "SELECT 9223372036854775807::BIGINT",
        "SELECT 5223372036854775807::BIGINT",
        "SELECT 0, CREATEDATE FROM _V_TABLE ORDER BY CREATEDATE DESC",
        "SELECT * FROM SYSTEM.ADMIN._T_ATTRIBUTE ORDER BY ROWID LIMIT 500",

        "SELECT * FROM SYSTEM.ADMIN._V_DATABASE ORDER BY OBJID",
        "SELECT * FROM SYSTEM.ADMIN._V_OBJECT_DATA ORDER BY OBJID",
        "SELECT * FROM SYSTEM.ADMIN._V_OBJECT_DATA_NO_OWNER ORDER BY OBJID",
        "SELECT * FROM JUST_DATA.ADMIN._V_RELATION_COLUMN ORDER BY OBJID, ATTNUM",
        "SELECT * FROM JUST_DATA.ADMIN._V_VIEW ORDER BY OBJID",
        "SELECT * FROM JUST_DATA.ADMIN._V_PROCEDURE ORDER BY OBJID",
        "SELECT * FROM JUST_DATA.._V_EXTERNAL ORDER BY RELID",
        "SELECT * FROM JUST_DATA.._V_EXTOBJECT ORDER BY OBJID",
        "SELECT * FROM JUST_DATA.._V_FUNCTION ORDER BY OBJID",
        "SELECT * FROM JUST_DATA.._V_SYNONYM ORDER BY OBJID",
        "SELECT * FROM JUST_DATA.._V_RELATION_KEYDATA",
        "SELECT * FROM JUST_DATA.._V_TABLE_DIST_MAP ORDER BY OBJID, DISTATTNUM",
        "SELECT * FROM JUST_DATA.._V_TABLE_ORGANIZE_COLUMN ORDER BY OBJID, ATTNAME",

        //to check null bitmaping
        "SELECT 1,null,null,null,null,null,null,2,3,4,5,6,null,null,null,null,8,null,null,null,9,10,12,13,15,null,26,null,null,null,null,null,null,null,null,null,null" +
        ",null,null,null,null,null,null,14,1,1,1,1,1,1,1,1,1,1,1,1,1,null,'aaaa','bbb',null,'ccc',null,null,null,null,null",
        "SELECT 1,null,null,now(),null,null,null,2,3,4,5,6,null,null,null,null,8,null,null,null,9,10,12,13,15,null,26,null,null,null,null,null,null,null,null,null,null" +
        ",null,null,null,now(),null,null,14,1,1,1,1,1,1,1,1,1,1,1,1,1,null,'aaaa','bbb',null,'ccc',null,null,null,null,null,'bbb',null,'ccc',null,null,null,null,null,'bbb',null,'ccc',null,null,null,null,null,7,8,9,10,11,12,13,14,15,16,17,18,19,20,null",


        "SELECT 1,null,null,null,null,null,null,2,3,4,5,6,null,null,null,null,8,null,null,null,9,10,12,13,15,null,26,null,null,null,null,null,null,null,null,null,null" +
        ",null,null,null,null,null,null,14,1,1,1,1,1,1,1,1,1,1,1,1,1,null,'aaaa','bbb',null,'ccc',null,null,null,null,null from FACTPRODUCTINVENTORY limit 1",
        "SELECT 1,null,null,now(),null,null,null,2,3,4,5,6,null,null,null,null,8,null,null,null,9,10,12,13,15,null,26,null,null,null,null,null,null,null,null,null,null" +
        ",null,null,null,now(),null,null,14,1,1,1,1,1,1,1,1,1,1,1,1,1,null,'aaaa','bbb',null,'ccc',null,null,null,null,null,'bbb',null,'ccc',null,null,null,null,null,'bbb',null,'ccc',null,null,null,null,null,7,8,9,10,11,12,13,14,15,16,17,18,19,20,null from FACTPRODUCTINVENTORY limit 1",

        //"SELECT * FROM SYSTEM.ADMIN._V_QUERYSTATUS ORDER BY OPID",
        //https://github.com/IBM/nzpy/issues/61
        "SELECT * FROM SYSTEM.ADMIN._V_TABLE_STORAGE_STAT WHERE OBJTYPE = 'TABLE'  ORDER BY OBJID",
        "SELECT * FROM SYSTEM.ADMIN._V_TABLE_ONLY_STORAGE_STAT WHERE OBJTYPE = 'TABLE' ORDER BY OBJID",
        "SELECT 123,NOW(),3.14::NUMERIC(20,4), 3.14::FLOAT, NOW(), CURRENT_DATE, CURRENT_TIMESTAMP,NULL",

        queryManyTypes,
        "SELECT 1,2,3,4::smallint,5,6,7,8,9,10,11,12,NULL,13,14,15,16,17,18,19,20,CURRENT_DATE,CURRENT_DATE,CURRENT_DATE,* FROM FACTPRODUCTINVENTORY FI ORDER BY ROWID LIMIT 1000",
        "SELECT '1111','2222','3333','55555',NULL,'6ĄŚŃĆŚŹŻ66666' FROM FACTPRODUCTINVENTORY FI ORDER BY ROWID LIMIT 1000",
        "SELECT NULL,3145,NULL::INT,2, NULL::CHAR(16),3,4,5,1,NULL::INT,2, NULL::CHAR(16),3,4,5,NULL::DOUBLE,NULL::NUMERIC(12),'#################' FROM JUST_DATA..DIMDATE ORDER BY ROWID LIMIT 1000",
        "SELECT * FROM JUST_DATA..NUMERIC_TEST ORDER BY ROWID LIMIT 1000",
        "SELECT 'śćźóć', 'abc'  FROM JUST_DATA..DIMACCOUNT ORDER BY ROWID LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.CUSTOMERADDRESS LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.CUSTOMERDATA LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMACCOUNT LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMCURRENCY LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMCUSTOMER LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMDEPARTMENTGROUP LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMEMPLOYEE LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMGEOGRAPHY LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMORGANIZATION LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMPRODUCT LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMPRODUCTCATEGORY LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMPRODUCTSUBCATEGORY LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMPROMOTION LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMRESELLER LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMSALESREASON LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMSALESTERRITORY LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.DIMSCENARIO LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.FACTADDITIONALINTERNATIONALPRODUCTDESCRIPTION LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.FACTCALLCENTER LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.FACTCURRENCYRATE LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.FACTFINANCE LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.FACTINTERNETSALES LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.FACTINTERNETSALESREASON LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.FACTPRODUCTINVENTORY LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.FACTRESELLERSALES LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.FACTSALESQUOTA LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.FACTSURVEYRESPONSE LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241207_1239XPCXOONYVU LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241213_1845MUMVFHYBCO LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241213_1847OUJJVLOPTY LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241213_1848FOREPWRBHB LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241213_1901QTZBPBZDHP LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241213_1902TIPEVMLJYB LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241213_1914ZJWASKLTSA LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241213_1915SJWBLKTPCC LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241213_1916EPRFGCYDUU LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241213_1921NKTCQXCTGL LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241225_1340SCDITAJDCU LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.IMP_241226_1143WFZOYOLPCP LIMIT 1000",
        "SELECT * FROM JUST_DATA.ADMIN.NEWFACTCURRENCYRATE LIMIT 1000",
        "SELECT DATASLICEID,DELETEXID, * FROM JUST_DATA..DIMACCOUNT  LIMIT 1000"
    ];

    private readonly string[] _queriesFromSystemTables =
[
"SELECT * FROM SYSTEM.ADMIN._T_OBJECT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_OBJECT_CLASSES ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_PROC ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_TYPE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_CLASS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_RELCHECK ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ATTRDEF ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_TRIGGER ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_INHERITS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_INDEX ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_STATISTIC ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_OPERATOR ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_OPCLASS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_AM ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_AMOP ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_AMPROC ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_LANGUAGE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_LARGEOBJECT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_AGGREGATE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_IPL ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_INHERITPROC ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REWRITE ORDER BY EV_CLASS DESC LIMIT 500",
//"SELECT * FROM SYSTEM.ADMIN._T_REWRITE ORDER BY EV_CLASS",
"SELECT * FROM SYSTEM.ADMIN._T_VIEW_USERSQL ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_LISTENER ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_DESCRIPTION ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_DIST_MAP ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ORGANIZE_ON ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_GROOM_HISTORY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_THIN ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ALTBASE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SELCACHE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_EXTERNAL ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_EXTOBJECT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_EXTTABALLOW ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_EXTZONES ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_CONSTRAINT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_CONST_RELATTR ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_CONST_REFATTR ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SYNONYM ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_BACKUP_GROUP ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_BACKUP_GROUP_MEMBER ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_RESTORE_ATTRESTOID ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_LIBRARY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_UDXATTRIBUTE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_UDXENVIRONMENT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SCHEMA ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_DATABASE ORDER BY ROWID LIMIT 500",
//"SELECT * FROM SYSTEM.ADMIN._T_VARIABLE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_USER ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_GROUP ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ROLE ORDER BY ROWID LIMIT 500",
//"SELECT * FROM SYSTEM.ADMIN._T_LOG ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ENV ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_GRPOBJ_PRIV ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_USROBJ_PRIV ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_GRPUSR ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SEC_OBJ ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ACL ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ODBC_FEATURE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_OLEDB_FEATURE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_JDBC_FEATURE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_DOTNET_FEATURE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ERROR_MSG ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_NODE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_SET ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_SET_NODE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_DATABASE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_BNR_REPL_DATABASE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_STATE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_MAX_CSN ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_TMP_REPL_NODE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_TMP_REPL_SET ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_TMP_REPL_SET_NODE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_TMP_REPL_STATE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_COMMIT_LOG ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_COMMIT_CAPTURED ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_EXTERNAL_FILE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_ROLE_TEXT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_STATE_TEXT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_DBSTATE_TEXT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_APPLY_LOG ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_CAPTURE_DBACCESS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_APPLY_DBACCESS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_TX_FORK ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_APPLY_DATAFILE_LOG ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_CAPTURE_TABLEACCESS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_CAPTURE_INVIS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_APPLY_MAP ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_APPLY_INVIS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_CAPTURE_BY_VALUE_LOAD ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_CAPTURE_SEQUENCE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_CAPTURE_EXTRA ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_APPLY_EXTRA ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_SET_NODE_V1 ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_TMP_REPL_SET_NODE_V1 ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_RECOVERY_STATE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_RECOVERY_STATE_TEXT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_SET_STATE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_REPL_NODE_STATE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_PLANSTATUS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_GROOM_STATUS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_GROOM_MODE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_DSLICE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HWCOMP ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HWEVENT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_EVENT_INFO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HWTYPETEXT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HWROLETEXT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HWSTATETEXT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SPUPARTITIONTYPETEXT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SPUPARTITION ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_LOGICALPARTITION ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_LUN ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SPUDEVICEMAP ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SCSI_PFE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SCSI_ERRORS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ECCERR ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_DFPGAERR ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HWFAILED ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_EVRULE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_EVTEMPLATE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ENVIRON ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_NBCONNECTOR ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SYSTEM_INFO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SPACOMP ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HWTRANSITINFO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SPUPARTTRANSITINFO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_LOGPARTTRANSITINFO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ETHSWSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ETHSWPORTSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ETHSWMNMTPORTSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_PHYSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_FANSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_BLOWERSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_EVENTPROXYWAITING ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_EVENTPROXYREPORTED ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HOSTRESOURCEINFO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HOSTETHSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HOSTDRBDSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HOSTCPUCORESTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HOSTFSSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HOSTCRMNODESTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HOSTMEMORYSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HOSTDISKSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HOSTSASSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HOSTPWRSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HOSTIMMSTATS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HWMON ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_QRYSTAT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_QRYHIST ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_V_TABLE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_V_VIEW ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_V_SPMVIEW ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_V_MATTHRESHOLD ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_VT_NZREV ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_VT_SCHED_GRA ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_VT_SCHED_SN ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_VT_SCHED_SYS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_VT_SYSTEM_UTIL ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_HIST_CONFIG ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SHOW_COHORT_HIERARCHY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_USER_SECURITY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_CRYPTO_KEYSTORE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_CRYPTO_KEY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_DFPGAERR_XS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_VECTOR_IDX ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_CLIENT_COMPATIBILITY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_MD_REGEN_ERRORS ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SYS_DATATYPE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_VIRTUAL ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SYSTEMDEF ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_KMIP_MAPPING ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_CONNECTION ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_PRIORITY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_CHARSET ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_COLLATION ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_TEMP_TABLE_INFO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_TEMP_TABLE_DTL ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_TEMP_TABLE_ATTR ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_TEMP_TABLE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_VREL ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_BACKUP_HISTORY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_RESTORE_HISTORY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_BACKUP_TXLIST ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_BACKUP_TABLE_HISTORY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_BACKUP_GROUP_HISTORY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_BACKUP_REPLINFO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_RESTORE_REPLINFO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_BACKUP_DIRINFO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_DEPEND ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_PASSWORD_HISTORY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_AUTOMAINT_HISTORY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SECURITY_LEVEL ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SECURITY_COHORT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SECURITY_CATEGORY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_MLS_TABLE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SECURITY_USER_COHORT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SECURITY_USER_CATEGORY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SECURITY_COHORT_HIERARCHY ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_ACCESS_TIME ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SCHED_RULE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SCHED_RULE_ATTR ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._T_SCHED_RULE_ATTR_VAL ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._VT_BASIC_DEMO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._VT_DUAL ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._VT_DUAL_DSLICE ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._VT_SPU_TABLE_INFO ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._VT_TBLDICT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._VT_DISK_LOG ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._VT_FPGA_LOG ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._VT_OSINTER_EVENT ORDER BY ROWID LIMIT 500",
"SELECT * FROM SYSTEM.ADMIN._VT_OSINTER_CMD",
"SELECT * FROM SYSTEM.ADMIN._VT_OSINTER_PLAN",
"SELECT * FROM SYSTEM.ADMIN._VT_OSINTER_TXID",
"SELECT * FROM SYSTEM.ADMIN._VT_SNIPPET_HISTORY",
"SELECT * FROM SYSTEM.ADMIN._VT_SCHED_EVENT",
"SELECT * FROM SYSTEM.ADMIN._VT_SCHED_WORK_QUEUE",
"SELECT * FROM SYSTEM.ADMIN._VT_SCHED_SN",
"SELECT * FROM SYSTEM.ADMIN._VT_SCHED_GRA",
"SELECT * FROM SYSTEM.ADMIN._VT_SYSTEM_UTIL",
"SELECT * FROM SYSTEM.ADMIN._VT_SCHED_SYS",
"SELECT * FROM SYSTEM.ADMIN._VT_SCHED_WORK_ITEM",
"SELECT * FROM SYSTEM.ADMIN._VT_SCHED_ID",
"SELECT * FROM SYSTEM.ADMIN._VT_OSINTER_ID",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_LOG",
"SELECT * FROM SYSTEM.ADMIN._VT_DISK_SMARTATTR",
"SELECT * FROM SYSTEM.ADMIN._VT_SCSI_LOG_SENSE",
"SELECT * FROM SYSTEM.ADMIN._VT_SCSI_LOG_SENSE_RAW",
"SELECT * FROM SYSTEM.ADMIN._VT_SCSI_REQUEST_SENSE",
"SELECT * FROM SYSTEM.ADMIN._VT_SCSI_DEFECTS",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_NODE",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_SCAN",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_RETURN",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_HASH",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_RESTRICT",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_PROJECT",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_SORT",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_HASHJOIN",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_AGGREGATE",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_DOWNLOADTABLE",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_SAVETEMP",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_DONE",
"SELECT * FROM SYSTEM.ADMIN._VT_PLAN_EXISTSJOIN",
"SELECT * FROM SYSTEM.ADMIN._VT_SPU_ZMAP_INFO",
"SELECT * FROM SYSTEM.ADMIN._VT_ZMAP_STAT",
"SELECT * FROM SYSTEM.ADMIN._VT_NZREV",
"SELECT * FROM SYSTEM.ADMIN._VT_DISK_ALLOC",
"SELECT * FROM SYSTEM.ADMIN._VT_DISK_PARTITION",
"SELECT * FROM SYSTEM.ADMIN._VT_SEQUENCE",
"SELECT * FROM SYSTEM.ADMIN._VT_RESERVED",
"SELECT * FROM SYSTEM.ADMIN._VT_ROLLBACK_STATUS",
"SELECT * FROM SYSTEM.ADMIN._VT_ROLLBACK_HISTORY",
"SELECT * FROM SYSTEM.ADMIN._VT_ROLLBACK_COST_ESTIMATE",
"SELECT * FROM SYSTEM.ADMIN._VT_TXUNFINISHED",
"SELECT * FROM SYSTEM.ADMIN._VT_TXJOURNAL",
"SELECT * FROM SYSTEM.ADMIN._VT_TXJOURNAL_DETAIL ORDER BY OBJID LIMIT 5000",
"SELECT * FROM SYSTEM.ADMIN._VT_TXJOPERATION",
"SELECT * FROM SYSTEM.ADMIN._VT_HOSTTXSTATE",
"SELECT * FROM SYSTEM.ADMIN._VT_SPUTXSTATE",
"SELECT * FROM SYSTEM.ADMIN._VT_SPU_HARDWARE_ERROR",
"SELECT * FROM SYSTEM.ADMIN._VT_DEFAULTCERRORTEXT",
"SELECT * FROM SYSTEM.ADMIN._VT_IOSTAT",
"SELECT * FROM SYSTEM.ADMIN._VT_GROOM_STEP",
"SELECT * FROM SYSTEM.ADMIN._VT_SPU_METADATA_TX",
"SELECT * FROM SYSTEM.ADMIN._VT_TRANSTBL_IOSTAT",
"SELECT * FROM SYSTEM.ADMIN._VT_TRANSTBL_CONTEXT",
"SELECT * FROM SYSTEM.ADMIN._VT_TRANSTBL_NAME",
"SELECT * FROM SYSTEM.ADMIN._VT_CTA_PAGE",
"SELECT * FROM SYSTEM.ADMIN._VT_CTA_COLUMN",
"SELECT * FROM SYSTEM.ADMIN._VT_CTA_ADAPT",
"SELECT * FROM SYSTEM.ADMIN._VT_ZMAP_EVENT",
"SELECT * FROM SYSTEM.ADMIN._VT_ZMAP_FLUSH_DETAIL",
"SELECT * FROM SYSTEM.ADMIN._VT_ZMAP_SCAN_DETAIL",
"SELECT * FROM SYSTEM.ADMIN._VT_ZMAP_COMPLETION",
"SELECT * FROM SYSTEM.ADMIN._VT_COLUMN_TYPE",
"SELECT * FROM SYSTEM.ADMIN._VT_ZMAP_RESTRICT_OP",
"SELECT * FROM SYSTEM.ADMIN._VT_ZMAP_INDEX",
"SELECT * FROM SYSTEM.ADMIN._VT_HASH_JOIN_TEMP_TABLE",
"SELECT * FROM SYSTEM.ADMIN._VT_FPGA_SETUP_BASIC",
"SELECT * FROM SYSTEM.ADMIN._VT_FPGA_TBL_DESC",
"SELECT * FROM SYSTEM.ADMIN._VT_FPGA_INST_DESC",
"SELECT * FROM SYSTEM.ADMIN._VT_FPGA_INST",
"SELECT * FROM SYSTEM.ADMIN._VT_FPGA_VIS",
"SELECT * FROM SYSTEM.ADMIN._VT_EMULATOR",
"SELECT * FROM SYSTEM.ADMIN._VT_DEVCHECK_STATUS",
"SELECT * FROM SYSTEM.ADMIN._VT_DEVCHECK_ERRORS",
"SELECT * FROM SYSTEM.ADMIN._VT_SCHED_RULE_ACTIVATION",
"SELECT * FROM SYSTEM.ADMIN._VT_SRC_LOG",
"SELECT * FROM SYSTEM.ADMIN._VT_SRC",
"SELECT * FROM SYSTEM.ADMIN._VT_SRC_TRANSIENT",
"SELECT * FROM SYSTEM.ADMIN._VT_SRC_DETAIL",
"SELECT * FROM SYSTEM.ADMIN._VT_SRCM_HASH",
"SELECT * FROM SYSTEM.ADMIN._VT_SRCM_INFO",
"SELECT * FROM SYSTEM.ADMIN._VT_SRCM_BASES",
"SELECT * FROM SYSTEM.ADMIN._VT_SRC_POLICY",
"SELECT * FROM SYSTEM.ADMIN._VT_JOB_PLAN",
"SELECT * FROM SYSTEM.ADMIN._VT_JOB_EVENT_TYPE",
"SELECT * FROM SYSTEM.ADMIN._VT_JOB_EVENT",
"SELECT * FROM SYSTEM.ADMIN._VT_FCOMM_CHANNEL_BUFFER_STAT",
"SELECT * FROM SYSTEM.ADMIN._VT_LP15_REPAIR_STATUS",
"SELECT * FROM SYSTEM.ADMIN._VT_LOAD_STATUS",
"SELECT * FROM SYSTEM.ADMIN._VT_SNIPPET_RESOURCE",
"SELECT * FROM SYSTEM.ADMIN._VT_SCHED_MISFIT_ID",
"SELECT * FROM SYSTEM.ADMIN._V_DUAL",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_GRA_EXT_LATEST",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_SYS_LATEST",
"SELECT * FROM SYSTEM.ADMIN._V_SYSTEM_UTIL",
"SELECT * FROM SYSTEM.ADMIN._V_PLAN_RESOURCE",
"SELECT * FROM SYSTEM.ADMIN._V_SNIPPET_RESOURCE",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_MISFIT_ID",
"SELECT * FROM SYSTEM.ADMIN._V_EXTAUTH_SYSTEM",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_RULE",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_RULE_ACTIVATION",
"SELECT * FROM SYSTEM.ADMIN._V_ROLLBACK_STATUS",
"SELECT * FROM SYSTEM.ADMIN._V_TXUNFINISHED",
"SELECT * FROM SYSTEM.ADMIN._V_DUAL_DSLICE",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_MVIEW_STAT",
"SELECT * FROM SYSTEM.ADMIN._V_MVIEW_REFR_STAT",
"SELECT * FROM SYSTEM.ADMIN._V_VIEW_STORAGE_STAT",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_EXTTYPEPAGES",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_GROOMSTATE",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_ORGSTATE",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_DS_ORGSTATE",
"SELECT * FROM SYSTEM.ADMIN._V_DISK_LOG",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_SN",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_GRA",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_SN_EXT",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_GRA_EXT",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_SYS",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_SN_LATEST",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_GRA_LATEST",
"SELECT * FROM SYSTEM.ADMIN._V_SCHED_SN_EXT_LATEST",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_STATE_UNIQ",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_SYNC",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_COMMIT_LOG",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_APPLY_LOG",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_CONFIG",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_PTS_UTILIZATION",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_MYNODE",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATED_DATABASE",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_TRANSACTION_FORK",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_APPLY_DATAFILE_LOG",
"SELECT * FROM SYSTEM.ADMIN._V_MD_REGEN_ERRORS",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_ZMAP_COLUMN_INFO",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_ZMAP_DSLICE_INFO",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_OBJECT_DSLICE_INFO",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_OBJECT_STORAGE_SZ1",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_OBJECT_STORAGE_SZ2",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_OBJECT_STORAGE_SIZE",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_TABLE_MVIEW_SIZE",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_MVIEW_BASE_SIZE",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_FUNCTION_COLUMNS3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_CLIENT_INFO",
"SELECT * FROM SYSTEM.ADMIN._V_PLANSTATUS",
"SELECT * FROM SYSTEM.ADMIN._V_GROOM_STATUS",
"SELECT * FROM SYSTEM.ADMIN._V_GROOM_HISTORY",
"SELECT * FROM SYSTEM.ADMIN._V_DELIM",
"SELECT * FROM SYSTEM.ADMIN._V_HIST_CONFIG",
"SELECT * FROM SYSTEM.ADMIN._V_SECURITY_LEVEL",
"SELECT * FROM SYSTEM.ADMIN._V_SECURITY_CATEGORY",
"SELECT * FROM SYSTEM.ADMIN._V_SECURITY_COHORT",
"SELECT * FROM SYSTEM.ADMIN._V_SECURITY_COHORT_HIERARCHY",
"SELECT * FROM SYSTEM.ADMIN._V_USER_SECURITY",
"SELECT * FROM SYSTEM.ADMIN._V_CRYPTO_KEYSTORE",
"SELECT * FROM SYSTEM.ADMIN._V_CRYPTO_KEYSTORE_VERBOSE",
"SELECT * FROM SYSTEM.ADMIN._V_CRYPTO_KEY",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_NODE",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_SET",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_SET_NODE",
"SELECT * FROM SYSTEM.ADMIN._V_REPLICATION_STATE",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_INDEXINFO2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_BESTROWIDENTIFIER2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PROCEDURES2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PROCEDURE_COLUMNS2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_FUNCTION2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_FUNCTION_COLUMNS2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_CATALOG3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_SCHEMA3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_TABLETYPES3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PKFK3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_COLUMNS3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PRIMARYKEYS3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_TABLES3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_TYPEINFO3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_DATATYPES3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_INDEXINFO3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_BESTROWIDENTIFIER3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PROCEDURES3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PROCEDURE_COLUMNS3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_FUNCTION3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_COLUMNS1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PRIMARYKEYS1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_TABLES1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_TYPEINFO1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_DATATYPES1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_INDEXINFO1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_BESTROWIDENTIFIER1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PROCEDURES1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PROCEDURE_COLUMNS1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_FUNCTION1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_FUNCTION_COLUMNS1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_CATALOG2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_SCHEMA2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_TABLETYPES2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PKFK2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_COLUMNS2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PRIMARYKEYS2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_TABLES2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_TYPEINFO2",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_DATATYPES2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PRIMARYKEYS2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PKFK2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PROCEDURES2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PROCEDURE_PARAMETERS2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PROCEDURE_COLUMNS2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_CATALOGS3",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_SCHEMAS3",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_TABLES3",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_VIEWS3",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_COLUMNS3",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PROCEDURES3",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PROCEDURE_PARAMETERS3",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PROCEDURE_COLUMNS3",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PKFK3",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PRIMARYKEYS3",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_FEATURE",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_CATALOG1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_SCHEMA1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_TABLETYPES1",
"SELECT * FROM SYSTEM.ADMIN._V_JDBC_PKFK1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_TYPES1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_DATATYPES1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_DATATYPES2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_DATATYPES3",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_TABLETYPES1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_CATALOGS1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_SCHEMAS1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_TABLES1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_COLUMNS1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_VIEWS1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PRIMARYKEYS1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PKFK1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PROCEDURES1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PROCEDURE_PARAMETERS1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_PROCEDURE_COLUMNS1",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_CATALOGS2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_SCHEMAS2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_TABLES2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_COLUMNS2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_VIEWS2",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_TABLES1",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_VIEWS1",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_COLUMNS1",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_PRIMARYKEYS1",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_FOREIGNKEYS1",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_PROCEDURES1",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_PROCEDURE_PARAMETERS1",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_PROCEDURE_COLUMNS1",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_CATALOGS2",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_SCHEMAS2",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_TABLES2",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_VIEWS2",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_COLUMNS2",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_PRIMARYKEYS2",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_FOREIGNKEYS2",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_PROCEDURES2",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_PROCEDURE_PARAMETERS2",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_PROCEDURE_COLUMNS2",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_FEATURE",
"SELECT * FROM SYSTEM.ADMIN._V_DOTNET_USERS",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_GETTYPEINFO2",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_TABLETYPES2",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_PROCEDURES2",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_PROCEDURECOLUMNS2",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_CATALOG3",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_SCHEMA3",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_TABLES3",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_PRIMARYKEYS3",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_FOREIGNKEYS3",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_STATISTICS3",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_COLUMNS3",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_SPECIALCOLUMNS3",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_GETTYPEINFO3",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_TABLETYPES3",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_PROCEDURES3",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_PROCEDURECOLUMNS3",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_FEATURE",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_TYPES1",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_CATALOGS1",
"SELECT * FROM SYSTEM.ADMIN._V_OLEDB_SCHEMAS1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_TABLES1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_PRIMARYKEYS1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_FOREIGNKEYS1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_STATISTICS1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_COLUMNS1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_SPECIALCOLUMNS1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_GETTYPEINFO1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_CATALOG1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_SCHEMA1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_TABLETYPES1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_PROCEDURES1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_PROCEDURECOLUMNS1",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_CATALOG2",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_SCHEMA2",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_TABLES2",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_PRIMARYKEYS2",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_FOREIGNKEYS2",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_STATISTICS2",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_COLUMNS2",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_SPECIALCOLUMNS2",
"SELECT * FROM SYSTEM.ADMIN._V_RELATION_COLUMN_DEF_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_DIST_MAP_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_VIEW_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_INDEX_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_COLUMNS_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_SEQUENCE_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_STATISTIC_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_EXTOBJECT_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_EXTERNAL_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_SYNONYM_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_CONSTRAINT_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_OBJ_CONSTRAINT_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_RELATION_KEYDATA_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_SCHEMA_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_OBJ_SCHEMA_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_SCHEMA_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_ODBC_FEATURE",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_TABLE_VERSION_ATTRS_FULL",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_TABLE_VERSION_ATTRS",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_TABLE_VERSION_ATTR_ADDED",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_TABLE_VERSION_ATTR_DROPPED",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_TABLE_VERSION_ATTR_ADD_DROPPED",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_TABLE_VERSION_CHGS",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_TABLE_VERSION_DEFN",
"SELECT * FROM SYSTEM.ADMIN._V_SYNONYM",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_DB_OWNER_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_RELATION_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_OBJ_RELATION_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_DEPEND",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_IDX_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_INDEX_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_CONSTRAINT_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_THIN_TABLE_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_THIN_TABLE_ORDER_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_RELATION_COLUMN_XDB",
"SELECT * FROM SYSTEM.ADMIN._V_ETHSW",
"SELECT * FROM SYSTEM.ADMIN._V_HOSTDISK",
"SELECT * FROM SYSTEM.ADMIN._V_HOSTSAS",
"SELECT * FROM SYSTEM.ADMIN._V_EVRULE",
"SELECT * FROM SYSTEM.ADMIN._V_EVTEMPLATE",
"SELECT * FROM SYSTEM.ADMIN._V_ECCERR",
"SELECT * FROM SYSTEM.ADMIN._V_DFPGAERR",
"SELECT * FROM SYSTEM.ADMIN._V_DFPGAERR_XS",
"SELECT * FROM SYSTEM.ADMIN._V_SCSI_PFE",
"SELECT * FROM SYSTEM.ADMIN._V_SCSI_ERRORS",
"SELECT * FROM SYSTEM.ADMIN._V_MATTHRESHOLD",
"SELECT * FROM SYSTEM.ADMIN._V_SPMVIEW",
"SELECT * FROM SYSTEM.ADMIN._V_BACKUP_HISTORY",
"SELECT * FROM SYSTEM.ADMIN._V_RESTORE_HISTORY",
"SELECT * FROM SYSTEM.ADMIN._V_BACKUP_TABLE_HISTORY",
"SELECT * FROM SYSTEM.ADMIN._V_BACKUP_GROUP",
"SELECT * FROM SYSTEM.ADMIN._V_BACKUP_GROUP_MEMBER",
"SELECT * FROM SYSTEM.ADMIN._V_BACKUP_GROUP_HISTORY",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_TABLE_VERSION_OBJECT_DEFN",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_TABLE_VERSION_REL",
"SELECT * FROM SYSTEM.ADMIN._V_DISK",
"SELECT * FROM SYSTEM.ADMIN._V_FPGA",
"SELECT * FROM SYSTEM.ADMIN._V_CPU",
"SELECT * FROM SYSTEM.ADMIN._V_FAN",
"SELECT * FROM SYSTEM.ADMIN._V_POWERSUPPLY",
"SELECT * FROM SYSTEM.ADMIN._V_HWTYPETEXT",
"SELECT * FROM SYSTEM.ADMIN._V_HWROLETEXT",
"SELECT * FROM SYSTEM.ADMIN._V_HWSTATETEXT",
"SELECT * FROM SYSTEM.ADMIN._V_QRYSTAT",
"SELECT * FROM SYSTEM.ADMIN._V_QRYHIST",
"SELECT * FROM SYSTEM.ADMIN._V_SYSTEM_INFO",
"SELECT * FROM SYSTEM.ADMIN._V_SPUPARTITION",
"SELECT * FROM SYSTEM.ADMIN._V_DSLICE",
"SELECT * FROM SYSTEM.ADMIN._V_LUN",
"SELECT * FROM SYSTEM.ADMIN._V_ETHSWPORT",
"SELECT * FROM SYSTEM.ADMIN._V_PHY",
"SELECT * FROM SYSTEM.ADMIN._V_ETHSWMNMTPORT",
"SELECT * FROM SYSTEM.ADMIN._V_SASSW",
"SELECT * FROM SYSTEM.ADMIN._V_MM",
"SELECT * FROM SYSTEM.ADMIN._V_BLOWER",
"SELECT * FROM SYSTEM.ADMIN._V_STATISTIC",
"SELECT * FROM SYSTEM.ADMIN._V_SYSTEMDEF",
"SELECT * FROM SYSTEM.ADMIN._V_AUTHENTICATION",
"SELECT * FROM SYSTEM.ADMIN._V_AUTHENTICATION_SETTINGS",
"SELECT * FROM SYSTEM.ADMIN._V_CONNECTION",
"SELECT * FROM SYSTEM.ADMIN._V_EXTOBJECT",
"SELECT * FROM SYSTEM.ADMIN._V_EXTZONES",
"SELECT * FROM SYSTEM.ADMIN._V_PRIORITY",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_CONSTRAINT",
"SELECT * FROM SYSTEM.ADMIN._V_OBJ_CONSTRAINT",
"SELECT * FROM SYSTEM.ADMIN._V_OBJS_OWNED",
"SELECT * FROM SYSTEM.ADMIN._V_HWCOMP",
"SELECT * FROM SYSTEM.ADMIN._V_SPUDEVICEMAP",
"SELECT * FROM SYSTEM.ADMIN._V_RACK",
"SELECT * FROM SYSTEM.ADMIN._V_SPA",
"SELECT * FROM SYSTEM.ADMIN._V_SPU",
"SELECT * FROM SYSTEM.ADMIN._V_SFI",
"SELECT * FROM SYSTEM.ADMIN._V_DISKENCLOSURE",
"SELECT * FROM SYSTEM.ADMIN._V_SESSION_VERSION",
"SELECT * FROM SYSTEM.ADMIN._V_HOST_VERSION",
"SELECT * FROM SYSTEM.ADMIN._V_CLIENT_COMPATIBILITY",
"SELECT * FROM SYSTEM.ADMIN._V_SEQUENCE",
"SELECT * FROM SYSTEM.ADMIN._V_VREL",
"SELECT * FROM SYSTEM.ADMIN._V_VIRTUAL",
"SELECT * FROM SYSTEM.ADMIN._V_VECTOR_IDX",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_MISCOBJS",
"SELECT * FROM SYSTEM.ADMIN._V_OBJ_MISCOBJS",
"SELECT * FROM SYSTEM.ADMIN._V_AGGREGATE",
"SELECT * FROM SYSTEM.ADMIN._V_OPERATOR",
"SELECT * FROM SYSTEM.ADMIN._V_LIBRARY",
"SELECT * FROM SYSTEM.ADMIN._V_FUNCTION",
"SELECT * FROM SYSTEM.ADMIN._V_RULES",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_ZMAP_COLUMN",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_ORGANIZE_COLUMN",
"SELECT * FROM SYSTEM.ADMIN._V_MVIEW",
"SELECT * FROM SYSTEM.ADMIN._V_INDEX",
"SELECT * FROM SYSTEM.ADMIN._V_DATATYPE",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_DATATYPE",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_COLUMNS",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_TABLE",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_VIEW",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_INDEX",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_PRIV",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_ROLE_PRIV",
"SELECT * FROM SYSTEM.ADMIN._V_ROLE_PRIV",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_GROUP_PRIV",
"SELECT * FROM SYSTEM.ADMIN._V_GROUP_PRIV",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_USER_PRIV",
"SELECT * FROM SYSTEM.ADMIN._V_USER_PRIV",
"SELECT * FROM SYSTEM.ADMIN._V_USER_ADMPRIV",
"SELECT * FROM SYSTEM.ADMIN._V_RELOBJCLASSES",
"SELECT * FROM SYSTEM.ADMIN._V_OBJECT",
"SELECT * FROM SYSTEM.ADMIN._V_CLASS",
"SELECT * FROM SYSTEM.ADMIN._V_CLASS2",
"SELECT * FROM SYSTEM.ADMIN._V_ATTRIBUTE",
"SELECT * FROM SYSTEM.ADMIN._V_ATTRIBUTE2",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_RELATION",
"SELECT * FROM SYSTEM.ADMIN._V_OBJ_RELATION",
"SELECT * FROM SYSTEM.ADMIN._V_OBJECTS",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_IDX",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_INDEX",
"SELECT * FROM SYSTEM.ADMIN._V_CONSTRAINT_DEPENDS",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_CONSTRAINT",
"SELECT * FROM SYSTEM.ADMIN._V_THIN_TABLE",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_THIN_ORDER",
"SELECT * FROM SYSTEM.ADMIN._V_THIN_TABLE_ORDER",
"SELECT * FROM SYSTEM.ADMIN._V_RELATION_COLUMN",
"SELECT * FROM SYSTEM.ADMIN._V_RELATION_COLUMN_DEF",
"SELECT * FROM SYSTEM.ADMIN._V_TABLE_DIST",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_OBJECT_DATA",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_DATABASE",
"SELECT * FROM SYSTEM.ADMIN._V_OBJ_DATABASE",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_GROUP",
"SELECT * FROM SYSTEM.ADMIN._V_OBJ_GROUP",
"SELECT * FROM SYSTEM.ADMIN._V_GROUP",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_ROLE",
"SELECT * FROM SYSTEM.ADMIN._V_OBJ_ROLE",
"SELECT * FROM SYSTEM.ADMIN._V_ROLE",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_USER",
"SELECT * FROM SYSTEM.ADMIN._V_OBJ_USER",
"SELECT * FROM SYSTEM.ADMIN._V_USER",
"SELECT * FROM SYSTEM.ADMIN._V_GROUPUSERS",
"SELECT * FROM SYSTEM.ADMIN._V_USERGROUPS",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_SCHEMA",
"SELECT * FROM SYSTEM.ADMIN._V_OBJ_SCHEMA",
"SELECT * FROM SYSTEM.ADMIN._V_SCHEMA",
"SELECT * FROM SYSTEM.ADMIN._V_ENVIRON",
"SELECT * FROM SYSTEM.ADMIN._V_BNR_CONNECTOR",
"SELECT * FROM SYSTEM.ADMIN._V_OBJECT_CAST",
"SELECT * FROM SYSTEM.ADMIN._V_ACL_DATA",
"SELECT * FROM SYSTEM.ADMIN._V_SYS_DB_OWNER"
];


    //, 'next should be 2 hours interval'
    //, '2 hours'::interval
    //, 'next should be 02:00:00 time'
    //, '02:00:00'::TIME
    //, 'next should null interval'
    //, null::interval

    [Theory]
    [InlineData("SELECT '2 years 5 hours 11 months 41 minutes 15 sec'::interval FROM JUST_DATA..DIMDATE LIMIT 1", "2 years 11 mons 05:41:15 String")]
    [InlineData("SELECT '5 hours 41 minutes  15 sec'::interval FROM JUST_DATA..DIMDATE LIMIT 1", "05:41:15 String")]
    [InlineData("SELECT '05:41:15'::TIME FROM JUST_DATA..DIMDATE LIMIT 1", "05:41:15 TimeSpan")]
    [InlineData("SELECT '2 years 5 hours 11 months 41 minutes 15 sec'::interval", "2 years 11 mons 05:41:15 String")]
    [InlineData("SELECT '5 hours 41 minutes  15 sec'::interval", "05:41:15 String")]
    [InlineData("SELECT '05:41:15'::TIME", "05:41:15 TimeSpan")]

    public void ExpectedIntervalTime(string value1, string expected)
    {
        using var cursor = _nzNewConnection.CreateCommand();
        cursor.CommandText = value1;
        var rdr = cursor.ExecuteReader();
        rdr.Read(); 
        var val1 = rdr.GetValue(0);
        var result = $"{val1} {val1.GetType().Name}";

        Assert.Equal(expected, result);
    }

    [Fact]
    private void RunQueriesBasic()
    {
        RunSpecificQueries(_queryListBasic);
    }

    [Fact]
    private void RunQueriesSystem()
    {
        //Random rnd = new Random();
        //var random5 = _queriesFromSystemTables.ToList().OrderBy(x => rnd.Next()).Take(5);
        //RunSpecificQueries(random5);
        //RunSpecificQueries(_queriesFromSystemTables.Skip(15).Take(5));
        RunSpecificQueries(_queriesFromSystemTables.Skip(15).Take(5));
    }

    [Fact]
    private void RunFullTypeCheck()
    {
        RunSpecificQueries(_queryListBasic, doValueCheck:false);
        RunSpecificQueries(_queriesFromSystemTables, doValueCheck: false);
    }


    private void RunSpecificQueries(IEnumerable<string> queries, bool doValueCheck = true)
    {
        foreach (var query in queries)
        {
            using var cursor = _nzNewConnection.CreateCommand();
            cursor.CommandText = query;
            var rdrNz = cursor.ExecuteReader();
            List<object[]> executedFromNewNzDriver = new();
            while (rdrNz.Read())
            {
                var row = new object[rdrNz.FieldCount];
                rdrNz.GetValues(row);
                executedFromNewNzDriver.Add(row);
            }

            using var cmd = _odbcConnection.CreateCommand();
            cmd.CommandText = query;
            using var reader = cmd.ExecuteReader();

            int odbcRowsCount = 0;
            while (reader.Read())
            {
                for (int i = 0; i < reader.FieldCount; i++)
                {
                    var valueFromOdbc = reader.GetValue(i);
                    var odbcStrVal = $"{valueFromOdbc.GetType()} - {valueFromOdbc}";
                    var typeOdbc = reader.GetFieldType(i);
                    var valueFromNewDriver = executedFromNewNzDriver[odbcRowsCount][i];
                    var typeNz = rdrNz.GetFieldType(i);
                    var nzStrVal = $"{valueFromNewDriver.GetType()} - {valueFromNewDriver}";

                    var strOdbc = valueFromOdbc.ToString();
                    var strNZ = valueFromNewDriver.ToString();
                    //ODBC trims to abaut 4k chars
                    if (strNZ?.Length > 4000)
                    {
                        strNZ = strNZ[0..4000];
                    }
                    if (strOdbc?.Length > 4000)
                    {
                        strOdbc = strOdbc[0..4000];
                    }
                    //abstime difference is allowed for 3 hours , drver specific behavior
                    if (doValueCheck)
                    {
                        if (valueFromOdbc is not DateTime t1 || valueFromNewDriver is not DateTime t2 || (t1 - t2).TotalHours >= 3)
                        {
                            Assert.Equal(strOdbc, strNZ);
                            Assert.Equal(valueFromOdbc.GetType(), valueFromNewDriver.GetType());
                        }
                    }

                    if (valueFromNewDriver.GetType() != typeof(DBNull))
                    {
                        Assert.Equal(valueFromNewDriver.GetType(), typeNz);
                        Assert.Equal(typeOdbc, typeNz);
                    }
                }
                odbcRowsCount++;
            }
            if (doValueCheck)
            {
                //row count should be equal
                Assert.Equal(odbcRowsCount, executedFromNewNzDriver.Count);
            }
        }
    }

    public void Dispose()
    {
        _odbcConnection.Dispose();
        _nzNewConnection.Dispose();
    }
}
